### ISSUE TITLE
Abstracts in publications

### ISSUE THREAD

**Issue by angriman** [networkit/networkit-website#16]
After pressing the "more" button of any paper in the section "Publications on Algorithms Available in NetworKit", only the abstract of NetworKit journal paper is shown. So, there is no way to read the abstract of the other papers.

**Comment by hmeyerhenke** [comment]
It is also very difficult to match a publication and its respective code contribution in NetworKit. We should make this matching process a lot easier. One way would be to have notebooks for that. Other suggestions?
