### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by manpen** [networkit/networkit-website#19]
Most of the links on https://networkit.github.io/index.html in the right "Clone from GitHub" block are broken and/or should be updated to https://github.com/networkit/networkit

**Comment by fabratu** [comment]
Seems to be fixed.

However I found some more links broken/debatable:

- https://networkit.github.io/get_started.html#installation -> "Build NetworKit from Source" 
  -  Refers to master branch, whereas Dev is default and got by cloning directly
- https://networkit.github.io/get_started.html -> "Contributions"
  -  The link to the mailing list leads to Cologne University mailing list repo, whereas "networkit" is not found anymore. Suggestion: https://sympa.cms.hu-berlin.de/sympa/subscribe/networkit
- https://networkit.github.io/features.html -> "Network Profiling" (internal link)
  -  The referenced textmark is not present
- https://networkit.github.io/features.html -> "Network Analytics"
  -  Open Link "Technical Report" with target _blank
- https://networkit.github.io/projects.html
  -  Link "pdf-file" is getting 404
