### ISSUE TITLE
Add paper citation on NetworKit page

### ISSUE THREAD

**Issue by j-adamczyk** [networkit/networkit-website#78]
I don't know if this is the right place for such request, but I published a paper utilizing NetworKit and would like it to be listed on the [Publications page](https://networkit.github.io/publications.html). Of course, NetworKit is cited in bibliography.

Paper: ["Strengthening Structural Baselines for Graph Classification Using Local Topological Profile" J. Adamczyk, W. Czech](https://link.springer.com/chapter/10.1007/978-3-031-36027-5_47).

[Arxiv preprint](https://arxiv.org/abs/2305.00724), [GitHub code](https://github.com/j-adamczyk/LTP)

**Comment by fabratu** [comment]
Hi,

I moved the issue here. We will look at it and update the publications page accordingly.
